services:
  claude-stonekin:
    container_name: ${CLAUDE_USER}-stonekin-dev
    hostname: ${CLAUDE_USER}-stonekin-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Standard workspace mount (project files)
      - ..:/workspace:cached
      
      # User-specific home mounts into container user's home
      - ../.claude/${CLAUDE_USER}/.gitconfig:/home/claudreyality/.gitconfig:ro
      - ../.claude/${CLAUDE_USER}/.ssh:/home/claudreyality/.ssh:ro
      - ../.claude/${CLAUDE_USER}/.history:/home/claudreyality/.history
      
      # Agent memory (separate from workspace and home)
      - ../memory:/memory:cached
    environment:
      # C-SYNTHESIS: Add required variable validation
      - CLAUDE_USER=${CLAUDE_USER:?CLAUDE_USER environment variable is required. Set it to your preferred user identifier.}
      - MEMORY_FILE_PATH=/memory/${CLAUDE_USER}
      - TERM=xterm-256color
      - SHELL=/bin/zsh
    
    # Keep container running
    command: sleep infinity
    
    networks:
      - stonekin-network
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

# Note: Named volumes are created automatically by Docker when referenced

networks:
  stonekin-network:
    driver: bridge
    name: stonekin-network